name = "microsoft-account-manager"
main = "worker/index.ts"
compatibility_date = "2026-04-06"
workers_dev = true

assets = { directory = "./dist", binding = "ASSETS" }

[vars]
ADMIN_USERNAME = "admin"

[[d1_databases]]
binding = "DB"
database_name = "account_manager_db"
database_id = "7c6500bb-37c1-4a0c-9586-1b1563cddec2"

[observability]
enabled = true
